### ISSUE TITLE
[1.20.1] Neoforge Compatibility?

### ISSUE THREAD

**Issue by tlitookilakin** [wolfieboy09/Mekanism-x-Northstar#2]
Neoforge only goes up to 47.1.106 for 1.20.1 versions, and this mod requires 47.3.X versions of forge, so it can't run on neoforge. Any chance of official neoforge support?

**Comment by wolfieboy09** [comment]
Hello!

I asked in the Neoforge server, and I was told the following:

> 1. One should just use Forge for 1.20.1
> 2. Compile against 47.1.3 to support both forge and neo on 1.20.1

I started the Neoforge compatibility. Will update you once it has been completed

**Comment by wolfieboy09** [comment]
NeoForge dropped support for `1.20.1`, and `47.1.3` keeps crashing sadly.
