### ISSUE TITLE
Game crashing

### ISSUE THREAD

**Issue by user3647** [wolfieboy09/Mekanism-x-Northstar#3]
I downloaded this mod on Modrinth and put it in a NEW 1.20.1 mod pack with these other mods: Botarium, Create, Create Crafts and Additions, Create New Age, Create Northstar, Create Numismatics, Distant Horizons, Geckolib, Iceberg, Mekanism, Mekanism Additions, Mekanism Generators, Mekanism Tools, and finally Mekanism x Create Northstar(this mod)

**Comment by user3647** [comment]
I tested this on the last version of the mod and it worked fine! Guess the newest version doesn’t work. It was asking for a higher version of forge than wasnt there so I went from Minecraft 1.20.1 to 1.20.2. This probably caused the error. I downgraded the mod version to the oldest and it worked fine.

**Comment by wolfieboy09** [comment]
I can change it where it can use a lower version of Forge

**Comment by wolfieboy09** [comment]
What mod version are you u

**Comment by wolfieboy09** [comment]
What mod version are you using, and what one failed? I can update the mod to use a lower version of Forge.

**Comment by user3647** [comment]
I was using the newest version, that didn’t work. It was asking for the higher forge so I changed Minecraft to 1.20.2 and it broke. The oldest one worked though, it didn’t ask for the too high version of forge. I think you should go on modrinth and check how high the forge version goes on a 1.20.1 mod pack. Then change it to that or lower

**Comment by wolfieboy09** [comment]
So what Forge version are you trying to use that keeps failing?

**Comment by wolfieboy09** [comment]
Working on getting the mod to work on `47.3.0`. It keeps crashing, yet newer versions work fine. Will release the next version once I get this working

**Comment by wolfieboy09** [comment]
Forge 47.3.10 is the version that does not crash. I will release the update and then close this

**Comment by wolfieboy09** [comment]
I got 47.3.0 loaded! Will publish

**Comment by wolfieboy09** [comment]
`1.20.1` should be fixed now (Modrinth live, CurseForge under review). Reopen this issue if you have any issues!
