### ISSUE TITLE
[crash] in 1.19.2

### ISSUE THREAD

**Issue by partglm** [wolfieboy09/Mekanism-x-Northstar#4]
hello, 

the mod don't load properly in 1.19.2
if you need more information just tell me

**Comment by wolfieboy09** [comment]
Hello, could you send the crash report and the debug.log file?

**Comment by partglm** [comment]
[debug.log](https://github.com/user-attachments/files/18265897/debug.log)
[latest.log](https://github.com/user-attachments/files/18265899/latest.log)
i play with many other mods so i don't know if it's the problem is the mod but when i disable it it's works so...

**Comment by wolfieboy09** [comment]
What about the crash report? I can tell you what mod was the issue

**Comment by partglm** [comment]
my bad there is the crash report
[crash-2024-12-28_16.26.33-fml.txt](https://github.com/user-attachments/files/18266616/crash-2024-12-28_16.26.33-fml.txt)

**Comment by wolfieboy09** [comment]
> `java.lang.NoSuchMethodException: dev.wolfieboy09.mek_x_star.MekanismNorthStar.<init>()`

Hm, so that is an issue with my mod.
I will get a fix of it now so it won't crash

**Comment by wolfieboy09** [comment]
Okay dokie, issue is fixed in `1.2.3` of `1.19.2`. I will close this issue once Curseforge and Modrinth approve

**Comment by wolfieboy09** [comment]
Update has released

**Comment by partglm** [comment]
hey i'm sorry but i use forge 43.4.0 and the mod require 43.4.5 or above so i want to know if you can change the minimun version of it ?
