### ISSUE TITLE
version of forge

### ISSUE THREAD

**Issue by partglm** [wolfieboy09/Mekanism-x-Northstar#5]
hey i'm sorry but i use forge 43.4.0 and the mod require 43.4.5 or above so i want to know if you can change the minimun version of it ?

_Originally posted by @partglm in https://github.com/wolfieboy09/Mekanism-x-Northstar/issues/4#issuecomment-2564819381_

**Comment by wolfieboy09** [comment]
Hi, I will change the requirement for Forge for the next version to 43.4.0

**Comment by partglm** [comment]
thx and i want to know but you have do the mod for fun or just your job need to know java so you have do a mod ?

**Comment by wolfieboy09** [comment]
I like to do modding for fun, and I've wanted to make Minecraft mods, and also expand my knowledge on Java (and modding for future mods)

**Comment by wolfieboy09** [comment]
Also, I remembered why I had forge set to `43.4.5` or higher. Anything lower then that and forge crashes for things I can't control. I don't know why, but it does that, so that's why `43.4.5` is the minimal version, and plus you would usually go to the latest forge version, or the required one as in this mod

**Comment by partglm** [comment]
thx

**Comment by wolfieboy09** [comment]
Upgrade forge, and you will be able to use this mod

**Comment by partglm** [comment]
yes thx i hope you the better for the rest of your life

**Comment by wolfieboy09** [comment]
1. Your orignal comment was `yes but i have a modpack in curseforge so i can't`
2. Let me see what I can do to get this fixed. I will try to (again) go to the Forge server and see what can be done

**Comment by wolfieboy09** [comment]
Okay, @partglm I found the issue and releasing the patch now

**Comment by partglm** [comment]
thx, and i have edit my comment bcz i have found how to do it
